### PR TITLE
Container runtime and developer environment

### PR DESCRIPTION
**Pull request by GDYendell**
- [x] Depends on #31

### CODE REVIEW

**Comment by GDYendell** [comment]
@JamesOHeaDLS this should be ready now. Could you try following the instructions and report back with any problems?

**Comment by JamesOHeaDLS** [comment]
As discussed in person, I think the only changes needed are to the README:

- Make it clear that > refers to the vscode command palette
- A note to say that if cmake gives an error, eg

```
[cmakeExecutable] CMake executable not found in cache. Checking again.
[proc] Executing command: /dls_sw/apps/cmake/3.26.2/bin/cmake --version
[proc] The command: /dls_sw/apps/cmake/3.26.2/bin/cmake --version failed with error: Error: spawn /dls_sw/apps/cmake/3.26.2/bin/cmake ENOENT
[proc] Executing command: /dls_sw/apps/cmake/3.26.2/bin/cmake -E capabilities
[proc] The command: /dls_sw/apps/cmake/3.26.2/bin/cmake -E capabilities failed with error: Error: spawn /dls_sw/apps/cmake/3.26.2/bin/cmake ENOENT
[main] Configuring project: eiger-detector
```
then to check that `CMake: Cmake Path` in user settings is set to just 'cmake'

- Remove the notes regarding tickit-devices, etc

**Comment by GDYendell** [comment]
I have update the README @JamesOHeaDLS, what do you think?

**Comment by JamesOHeaDLS** [comment]
README is good, thanks!

**Pull request merged**
